spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: when_authorized
