SET REFERENTIAL_INTEGRITY FALSE;

CREATE TABLE account_action_token (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  purpose varchar(32) NOT NULL,
  token_hash varchar(128) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  expires_at timestamp NOT NULL,
  consumed_at timestamp NULL DEFAULT NULL,
  invalidated_at timestamp NULL DEFAULT NULL,
  metadata_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_account_action_token_hash (token_hash),
  KEY idx_account_action_token_user_purpose_status (user_id,purpose,status,expires_at)
);
CREATE TABLE achievement (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  achievement_code varchar(64) NOT NULL,
  unlocked tinyint(1) NOT NULL DEFAULT '0',
  progress_value int NOT NULL DEFAULT '0',
  target_value int NOT NULL DEFAULT '0',
  awarded_at timestamp NULL DEFAULT NULL,
  last_calculated_at timestamp NULL DEFAULT NULL,
  metadata_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_owner_user_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then owner_user_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_achievement_owner_code (active_owner_user_id,achievement_code),
  KEY idx_achievement_owner_unlocked (owner_user_id,unlocked,awarded_at)
);
CREATE TABLE admin_ai_config (
  id bigint NOT NULL AUTO_INCREMENT,
  config_key varchar(64) NOT NULL,
  encrypted_config longtext NOT NULL,
  version_number bigint NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_admin_ai_config_key (config_key)
);
CREATE TABLE admin_ai_config_history (
  id bigint NOT NULL AUTO_INCREMENT,
  config_key varchar(64) NOT NULL,
  version_number bigint NOT NULL,
  previous_version_number bigint DEFAULT NULL,
  encrypted_config longtext NOT NULL,
  change_summary_json longtext NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_admin_ai_config_history_key_version (config_key,version_number)
);
CREATE TABLE ai_conversation_message (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_session_id bigint NOT NULL,
  role varchar(16) NOT NULL,
  content_text longtext NOT NULL,
  payload_json longtext,
  request_id varchar(64) DEFAULT NULL,
  generation_source varchar(32) DEFAULT NULL,
  model varchar(128) DEFAULT NULL,
  grounded tinyint(1) DEFAULT NULL,
  fallback_reason varchar(128) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_ai_conversation_message_session_created_at (conversation_session_id,created_at)
);
CREATE TABLE ai_conversation_session (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_id varchar(64) NOT NULL,
  scene varchar(64) NOT NULL,
  student_user_id bigint NOT NULL,
  title varchar(128) NOT NULL,
  last_message_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_conversation_session_conversation_id (conversation_id),
  KEY idx_ai_conversation_session_student_scene_last_message (student_user_id,scene,last_message_at)
);
CREATE TABLE ai_async_job (
  id bigint NOT NULL AUTO_INCREMENT,
  job_id varchar(64) NOT NULL,
  user_id bigint NOT NULL,
  scene varchar(64) NOT NULL,
  status varchar(32) NOT NULL,
  request_json longtext NOT NULL,
  result_json longtext,
  error_message varchar(1000) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at timestamp NULL DEFAULT NULL,
  finished_at timestamp NULL DEFAULT NULL,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_async_job_job_id (job_id),
  KEY idx_ai_async_job_user_created (user_id, created_at),
  KEY idx_ai_async_job_status_created (status, created_at)
);
CREATE TABLE ai_generation_record (
  id bigint NOT NULL AUTO_INCREMENT,
  request_id varchar(64) NOT NULL,
  scene varchar(64) NOT NULL,
  student_user_id bigint DEFAULT NULL,
  teacher_user_id bigint DEFAULT NULL,
  teaching_class_id bigint DEFAULT NULL,
  diagnosis_summary_id bigint DEFAULT NULL,
  training_session_id bigint DEFAULT NULL,
  intervention_record_id bigint DEFAULT NULL,
  practice_session_id bigint DEFAULT NULL,
  prompt_version varchar(64) NOT NULL,
  model varchar(128) DEFAULT NULL,
  provider_request_id varchar(128) DEFAULT NULL,
  latency_ms bigint NOT NULL DEFAULT '0',
  token_usage_json longtext,
  input_payload_json longtext NOT NULL,
  raw_response_json longtext,
  validated_output_json longtext NOT NULL,
  generation_source varchar(32) NOT NULL,
  fallback_reason varchar(128) DEFAULT NULL,
  generated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_generation_record_request_id (request_id),
  KEY fk_ai_generation_record_class_id (teaching_class_id),
  KEY fk_ai_generation_record_diagnosis_summary_id (diagnosis_summary_id),
  KEY fk_ai_generation_record_training_session_id (training_session_id),
  KEY fk_ai_generation_record_intervention_record_id (intervention_record_id),
  KEY fk_ai_generation_record_practice_session_id (practice_session_id),
  KEY idx_ai_generation_record_scene_generated_at (scene,generated_at),
  KEY idx_ai_generation_record_student_scene (student_user_id,scene,generated_at),
  KEY idx_ai_generation_record_teacher_scene (teacher_user_id,scene,generated_at)
);
CREATE TABLE analytics_daily_aggregate (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  stat_date date NOT NULL,
  week_start_date date NOT NULL,
  source_type varchar(16) NOT NULL,
  aggregation_level varchar(16) NOT NULL,
  lexical_pair_id bigint NOT NULL DEFAULT '0',
  lexical_pair_type varchar(32) NOT NULL DEFAULT 'ALL',
  training_mode varchar(32) NOT NULL DEFAULT 'ALL',
  context_support_level varchar(16) NOT NULL DEFAULT 'ALL',
  attempt_count int NOT NULL DEFAULT '0',
  correct_count int NOT NULL DEFAULT '0',
  incorrect_count int NOT NULL DEFAULT '0',
  total_reaction_time_ms bigint NOT NULL DEFAULT '0',
  total_hesitation_time_ms bigint NOT NULL DEFAULT '0',
  positive_transfer_score_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  negative_transfer_risk_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  context_sensitivity_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  semantic_discrimination_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  high_risk_count int NOT NULL DEFAULT '0',
  pending_review_count int NOT NULL DEFAULT '0',
  completion_count int NOT NULL DEFAULT '0',
  false_friend_confusion_count int NOT NULL DEFAULT '0',
  context_ignored_count int NOT NULL DEFAULT '0',
  over_transfer_count int NOT NULL DEFAULT '0',
  under_transfer_count int NOT NULL DEFAULT '0',
  orthographic_interference_count int NOT NULL DEFAULT '0',
  semantic_misfire_count int NOT NULL DEFAULT '0',
  last_event_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_owner_user_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then owner_user_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_analytics_daily_aggregate (active_owner_user_id,stat_date,source_type,aggregation_level,lexical_pair_id,lexical_pair_type,training_mode,context_support_level),
  KEY idx_analytics_daily_aggregate_owner_date (owner_user_id,stat_date),
  KEY idx_analytics_daily_aggregate_owner_week (owner_user_id,week_start_date),
  KEY idx_analytics_daily_aggregate_owner_pair_type_date (owner_user_id,lexical_pair_type,stat_date)
);
CREATE TABLE assessment_attempt (
  id bigint NOT NULL AUTO_INCREMENT,
  publish_id bigint NOT NULL,
  paper_id bigint NOT NULL,
  student_user_id bigint DEFAULT NULL,
  participant_id bigint DEFAULT NULL,
  status varchar(32) NOT NULL DEFAULT 'IN_PROGRESS',
  started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp NOT NULL,
  submitted_at timestamp NULL DEFAULT NULL,
  last_saved_at timestamp NULL DEFAULT NULL,
  answered_count int NOT NULL DEFAULT '0',
  objective_score int NOT NULL DEFAULT '0',
  total_score int NOT NULL DEFAULT '0',
  version bigint NOT NULL DEFAULT '1',
  submit_reason varchar(32) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_publish_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then publish_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_attempt_publish_student (active_publish_id,student_user_id),
  KEY fk_assessment_attempt_paper_id (paper_id),
  KEY idx_assessment_attempt_student_status (student_user_id,status,started_at),
  KEY idx_assessment_attempt_publish_status (publish_id,status,started_at)
);
CREATE TABLE assessment_attempt_answer (
  id bigint NOT NULL AUTO_INCREMENT,
  attempt_id bigint NOT NULL,
  question_id bigint NOT NULL,
  question_order int NOT NULL,
  question_type varchar(32) NOT NULL,
  stem_text_snapshot varchar(2000) NOT NULL,
  prompt_text_snapshot varchar(1000) DEFAULT NULL,
  options_json_snapshot longtext,
  correct_answer_json longtext NOT NULL,
  explanation_text_snapshot varchar(1000) DEFAULT NULL,
  question_score int NOT NULL DEFAULT '0',
  response_json longtext,
  justification_text varchar(2000) DEFAULT NULL,
  spelling_wrong_attempt_count int NOT NULL DEFAULT 0,
  spelling_hint_shown_at timestamp NULL DEFAULT NULL,
  first_presented_at timestamp NULL DEFAULT NULL,
  first_answered_at timestamp NULL DEFAULT NULL,
  effective_duration_ms bigint NOT NULL DEFAULT 0,
  response_change_count int NOT NULL DEFAULT 0,
  answered tinyint(1) NOT NULL DEFAULT '0',
  correct tinyint(1) DEFAULT NULL,
  score_awarded int DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_attempt_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then attempt_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_attempt_answer_order (active_attempt_id,question_order),
  KEY fk_assessment_attempt_answer_question_id (question_id),
  KEY idx_assessment_attempt_answer_attempt_order (attempt_id,question_order)
);
CREATE TABLE assessment_paper (
  id bigint NOT NULL AUTO_INCREMENT,
  paper_code varchar(64) NOT NULL,
  title varchar(255) NOT NULL,
  description varchar(1000) DEFAULT NULL,
  owner_user_id bigint NOT NULL,
  paper_purpose varchar(32) NOT NULL DEFAULT 'CLASS_ASSESSMENT',
  status varchar(32) NOT NULL DEFAULT 'DRAFT',
  duration_minutes int NOT NULL DEFAULT '30',
  question_count int NOT NULL DEFAULT '0',
  total_score int NOT NULL DEFAULT '0',
  latest_publish_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_paper_code (paper_code),
  KEY idx_assessment_paper_purpose (paper_purpose,owner_user_id,status,updated_at),
  KEY idx_assessment_paper_owner_status (owner_user_id,status,updated_at)
);
CREATE TABLE assessment_publish (
  id bigint NOT NULL AUTO_INCREMENT,
  paper_id bigint NOT NULL,
  teaching_class_id bigint DEFAULT NULL,
  delivery_mode varchar(32) NOT NULL DEFAULT 'CLASS',
  published_by bigint NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'PUBLISHED',
  paper_title_snapshot varchar(255) NOT NULL,
  paper_description_snapshot varchar(1000) DEFAULT NULL,
  question_count_snapshot int NOT NULL DEFAULT '0',
  total_score_snapshot int NOT NULL DEFAULT '0',
  duration_minutes int NOT NULL,
  instructions_text varchar(1000) DEFAULT NULL,
  starts_at timestamp NULL DEFAULT NULL,
  due_at timestamp NULL DEFAULT NULL,
  result_release_policy varchar(32) NOT NULL DEFAULT 'IMMEDIATE',
  published_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY fk_assessment_publish_published_by (published_by),
  KEY idx_assessment_publish_class_status (teaching_class_id,status,due_at),
  KEY idx_assessment_publish_paper_time (paper_id,published_at)
);
CREATE TABLE assessment_publish_recipient (
  id bigint NOT NULL AUTO_INCREMENT,
  publish_id bigint NOT NULL,
  paper_id bigint NOT NULL,
  teaching_class_id bigint NOT NULL,
  student_user_id bigint NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_publish_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then publish_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_publish_recipient_publish_student (active_publish_id,student_user_id),
  KEY fk_assessment_publish_recipient_paper_id (paper_id),
  KEY fk_assessment_publish_recipient_class_id (teaching_class_id),
  KEY idx_assessment_publish_recipient_publish (publish_id,student_user_id),
  KEY idx_assessment_publish_recipient_student (student_user_id,publish_id)
);
CREATE TABLE assessment_question (
  id bigint NOT NULL AUTO_INCREMENT,
  paper_id bigint NOT NULL,
  question_type varchar(32) NOT NULL,
  sort_order int NOT NULL DEFAULT '1',
  stem_text varchar(2000) NOT NULL,
  prompt_text varchar(1000) DEFAULT NULL,
  options_json longtext,
  correct_answer_json longtext NOT NULL,
  explanation_text varchar(1000) DEFAULT NULL,
  score int NOT NULL DEFAULT '10',
  question_version_id bigint DEFAULT NULL,
  section_code varchar(64) DEFAULT NULL,
  required_answer tinyint(1) NOT NULL DEFAULT '1',
  weight decimal(10,4) NOT NULL DEFAULT '1.0000',
  transfer_category varchar(32) DEFAULT NULL,
  context_level varchar(32) DEFAULT NULL,
  construct_code varchar(64) DEFAULT NULL,
  target_word varchar(255) DEFAULT NULL,
  option_explanations_json longtext,
  display_condition_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_assessment_question_paper_order (paper_id,sort_order)
);
CREATE TABLE assessment_question_bank (
  id bigint NOT NULL AUTO_INCREMENT,
  bank_code varchar(64) NOT NULL,
  name varchar(255) NOT NULL,
  description varchar(1000) DEFAULT NULL,
  owner_user_id bigint NOT NULL,
  visibility varchar(32) NOT NULL DEFAULT 'SHARED',
  status varchar(32) NOT NULL DEFAULT 'ACTIVE',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_question_bank_code (bank_code),
  KEY idx_assessment_question_bank_owner_status (owner_user_id,status,updated_at)
);
CREATE TABLE assessment_question_version (
  id bigint NOT NULL AUTO_INCREMENT,
  question_bank_id bigint NOT NULL,
  question_code varchar(64) NOT NULL,
  version_no int NOT NULL,
  question_type varchar(48) NOT NULL,
  stem_text longtext,
  prompt_text longtext,
  options_json longtext,
  correct_answer_json longtext,
  explanation_text longtext,
  option_explanations_json longtext,
  required_answer tinyint(1) NOT NULL DEFAULT '1',
  weight decimal(10,4) NOT NULL DEFAULT '1.0000',
  transfer_category varchar(32) DEFAULT NULL,
  context_level varchar(32) DEFAULT NULL,
  construct_code varchar(64) DEFAULT NULL,
  target_word varchar(255) DEFAULT NULL,
  display_condition_json longtext,
  source_reference varchar(512) DEFAULT NULL,
  content_hash char(64) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_question_version_code (question_bank_id,question_code,version_no),
  UNIQUE KEY uk_assessment_question_version_hash (question_bank_id,content_hash),
  KEY idx_assessment_question_version_tags (transfer_category,context_level,construct_code)
);
CREATE TABLE assessment_questionnaire (
  id bigint NOT NULL AUTO_INCREMENT,
  questionnaire_code varchar(64) NOT NULL,
  title varchar(255) NOT NULL,
  description varchar(1000) DEFAULT NULL,
  owner_user_id bigint NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'DRAFT',
  latest_version_no int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_questionnaire_code (questionnaire_code),
  KEY idx_assessment_questionnaire_owner_status (owner_user_id,status,updated_at)
);
CREATE TABLE assessment_questionnaire_version (
  id bigint NOT NULL AUTO_INCREMENT,
  questionnaire_id bigint NOT NULL,
  paper_id bigint NOT NULL,
  version_no int NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'DRAFT',
  scoring_version varchar(64) NOT NULL DEFAULT 'SCORING_V1',
  ai_prompt_version varchar(64) NOT NULL DEFAULT 'assessment-analysis/v2',
  source_package_code varchar(64) DEFAULT NULL,
  published_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_questionnaire_version_no (questionnaire_id,version_no),
  UNIQUE KEY uk_assessment_questionnaire_version_paper (paper_id),
  KEY idx_assessment_questionnaire_version_status (questionnaire_id,status,version_no)
);
CREATE TABLE assessment_questionnaire_section (
  id bigint NOT NULL AUTO_INCREMENT,
  questionnaire_version_id bigint NOT NULL,
  section_code varchar(64) NOT NULL,
  title varchar(255) NOT NULL,
  description varchar(1000) DEFAULT NULL,
  shared_material longtext,
  sort_order int NOT NULL,
  formal_section tinyint(1) NOT NULL DEFAULT '1',
  scored_item_count int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_questionnaire_section_code (questionnaire_version_id,section_code),
  UNIQUE KEY uk_assessment_questionnaire_section_order (questionnaire_version_id,sort_order)
);
CREATE TABLE assessment_questionnaire_item (
  id bigint NOT NULL AUTO_INCREMENT,
  questionnaire_version_id bigint NOT NULL,
  section_id bigint NOT NULL,
  assessment_question_id bigint NOT NULL,
  question_version_id bigint DEFAULT NULL,
  item_code varchar(64) NOT NULL,
  required_answer tinyint(1) NOT NULL DEFAULT '1',
  scored tinyint(1) NOT NULL DEFAULT '1',
  weight decimal(10,4) NOT NULL DEFAULT '1.0000',
  transfer_category varchar(32) DEFAULT NULL,
  context_level varchar(32) DEFAULT NULL,
  construct_code varchar(64) DEFAULT NULL,
  target_word varchar(255) DEFAULT NULL,
  option_explanations_json longtext,
  display_condition_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_questionnaire_item_code (questionnaire_version_id,item_code),
  UNIQUE KEY uk_assessment_questionnaire_item_question (assessment_question_id),
  KEY idx_assessment_questionnaire_item_section (section_id,assessment_question_id),
  KEY fk_assessment_questionnaire_item_qversion (question_version_id)
);
CREATE TABLE assessment_public_release (
  id bigint NOT NULL AUTO_INCREMENT,
  publish_id bigint NOT NULL,
  release_code varchar(32) NOT NULL,
  code_count int NOT NULL,
  session_ttl_hours int NOT NULL DEFAULT '12',
  qr_entry_enabled tinyint(1) NOT NULL DEFAULT '0',
  status varchar(32) NOT NULL DEFAULT 'PUBLISHED',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_public_release_publish (publish_id),
  UNIQUE KEY uk_assessment_public_release_code (release_code)
);
CREATE TABLE assessment_participation_code (
  id bigint NOT NULL AUTO_INCREMENT,
  public_release_id bigint NOT NULL,
  code_digest char(64) NOT NULL,
  code_hint varchar(4) DEFAULT NULL,
  status varchar(32) NOT NULL DEFAULT 'UNUSED',
  export_batch_id varchar(64) DEFAULT NULL,
  exported_at timestamp NULL DEFAULT NULL,
  first_verified_at timestamp NULL DEFAULT NULL,
  last_verified_at timestamp NULL DEFAULT NULL,
  submitted_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_participation_code_digest (code_digest),
  KEY idx_assessment_participation_code_release_status (public_release_id,status,id),
  KEY idx_assessment_participation_code_release_batch_status (public_release_id,export_batch_id,status,id)
);
CREATE TABLE assessment_participant (
  id bigint NOT NULL AUTO_INCREMENT,
  publish_id bigint NOT NULL,
  participant_type varchar(32) NOT NULL,
  user_id bigint DEFAULT NULL,
  participation_code_id bigint DEFAULT NULL,
  attempt_id bigint DEFAULT NULL,
  browser_fingerprint_digest char(64) DEFAULT NULL,
  sensitive_profile_ciphertext longtext,
  sensitive_profile_iv varchar(128) DEFAULT NULL,
  sensitive_profile_key_version varchar(64) DEFAULT NULL,
  consented_at timestamp NULL DEFAULT NULL,
  anonymized_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_participant_publish_user (publish_id,user_id),
  UNIQUE KEY uk_assessment_participant_publish_code (publish_id,participation_code_id),
  UNIQUE KEY uk_assessment_participant_publish_fingerprint (publish_id,participant_type,browser_fingerprint_digest),
  UNIQUE KEY uk_assessment_participant_attempt (attempt_id),
  KEY idx_assessment_participant_publish_type (publish_id,participant_type,id)
);
CREATE TABLE assessment_participant_access (
  id bigint NOT NULL AUTO_INCREMENT,
  public_release_id bigint NOT NULL,
  participant_id bigint NOT NULL,
  participation_code_id bigint DEFAULT NULL,
  access_mode varchar(32) NOT NULL,
  ip_ciphertext longtext NOT NULL,
  ip_iv varchar(128) NOT NULL,
  ip_key_version varchar(64) NOT NULL,
  accessed_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_assessment_participant_access_release_time (public_release_id,accessed_at,id),
  KEY idx_assessment_participant_access_code_time (participation_code_id,accessed_at,id),
  KEY idx_assessment_participant_access_participant_time (participant_id,accessed_at,id)
);
CREATE TABLE assessment_participant_session (
  id bigint NOT NULL AUTO_INCREMENT,
  participant_id bigint NOT NULL,
  session_token_digest char(64) NOT NULL,
  expires_at timestamp NOT NULL,
  last_seen_at timestamp NULL DEFAULT NULL,
  revoked_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_participant_session_token (session_token_digest),
  KEY idx_assessment_participant_session_expiry (participant_id,expires_at,revoked_at)
);
CREATE TABLE assessment_question_bank_import (
  id bigint NOT NULL AUTO_INCREMENT,
  question_bank_id bigint DEFAULT NULL,
  import_key varchar(64) NOT NULL,
  source_file_name varchar(255) NOT NULL,
  source_format varchar(16) NOT NULL,
  source_sha256 char(64) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'UPLOADED',
  source_payload_json longtext NOT NULL,
  preflight_summary_json longtext,
  differences_json longtext,
  errors_json longtext,
  confirmed_by bigint DEFAULT NULL,
  confirmed_at timestamp NULL DEFAULT NULL,
  committed_by bigint DEFAULT NULL,
  committed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_question_bank_import_key (import_key),
  KEY idx_assessment_question_bank_import_status (status,created_at),
  KEY fk_assessment_question_bank_import_bank (question_bank_id)
);
CREATE TABLE assessment_content_review_issue (
  id bigint NOT NULL AUTO_INCREMENT,
  import_id bigint NOT NULL,
  question_version_id bigint DEFAULT NULL,
  issue_code varchar(64) NOT NULL,
  severity varchar(32) NOT NULL DEFAULT 'REVIEW_REQUIRED',
  status varchar(32) NOT NULL DEFAULT 'OPEN',
  source_reference varchar(512) DEFAULT NULL,
  description varchar(2000) NOT NULL,
  source_value_json longtext,
  candidate_value_json longtext,
  resolved_by bigint DEFAULT NULL,
  resolved_at timestamp NULL DEFAULT NULL,
  resolution_note varchar(2000) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_assessment_content_review_issue_import (import_id,status,severity),
  KEY fk_assessment_content_review_issue_question (question_version_id)
);
CREATE TABLE assessment_timing_event (
  id bigint NOT NULL AUTO_INCREMENT,
  attempt_id bigint NOT NULL,
  question_id bigint NOT NULL,
  client_event_id varchar(64) NOT NULL,
  event_type varchar(32) NOT NULL,
  effective_delta_ms int NOT NULL DEFAULT '0',
  client_occurred_at timestamp NULL DEFAULT NULL,
  first_presented_at timestamp NULL DEFAULT NULL,
  first_answered_at timestamp NULL DEFAULT NULL,
  modification_count int NOT NULL DEFAULT '0',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_timing_event_client (attempt_id,client_event_id),
  KEY idx_assessment_timing_event_question (attempt_id,question_id,created_at),
  CONSTRAINT ck_assessment_timing_event_delta CHECK (effective_delta_ms >= 0 AND effective_delta_ms <= 30000)
);
CREATE TABLE assessment_metric_snapshot (
  id bigint NOT NULL AUTO_INCREMENT,
  attempt_id bigint NOT NULL,
  metric_version varchar(64) NOT NULL,
  scoring_version varchar(64) NOT NULL DEFAULT 'SCORING_V1',
  raw_score decimal(12,4) NOT NULL,
  max_score decimal(12,4) NOT NULL,
  percentage_score decimal(8,4) DEFAULT NULL,
  metrics_json longtext NOT NULL,
  quality_flags_json longtext NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_metric_snapshot_version (attempt_id,metric_version),
  KEY idx_assessment_metric_snapshot_attempt (attempt_id,created_at)
);
CREATE TABLE assessment_ai_analysis (
  id bigint NOT NULL AUTO_INCREMENT,
  attempt_id bigint NOT NULL,
  metric_snapshot_id bigint NOT NULL,
  prompt_version varchar(64) NOT NULL,
  idempotency_key varchar(191) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  retry_count int NOT NULL DEFAULT '0',
  model_name varchar(128) DEFAULT NULL,
  prompt_tokens int DEFAULT NULL,
  completion_tokens int DEFAULT NULL,
  analysis_json longtext,
  rule_fallback_json longtext,
  raw_response longtext,
  fallback_reason varchar(1000) DEFAULT NULL,
  generation_record_id bigint DEFAULT NULL,
  next_retry_at timestamp NULL DEFAULT NULL,
  completed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_assessment_ai_analysis_idempotency (idempotency_key),
  UNIQUE KEY uk_assessment_ai_analysis_version (attempt_id,metric_snapshot_id,prompt_version),
  KEY idx_assessment_ai_analysis_status_retry (status,next_retry_at,retry_count),
  KEY fk_assessment_ai_analysis_generation (generation_record_id)
);
CREATE TABLE audit_log (
  id bigint NOT NULL AUTO_INCREMENT,
  actor_user_id bigint DEFAULT NULL,
  action_type varchar(64) NOT NULL,
  target_type varchar(64) NOT NULL,
  target_id varchar(128) DEFAULT NULL,
  request_path varchar(255) NOT NULL,
  request_method varchar(16) NOT NULL,
  trace_id varchar(64) NOT NULL,
  request_payload text,
  response_code varchar(32) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_audit_log_deleted_created_id (deleted,created_at,id),
  KEY idx_audit_log_created_at (created_at),
  KEY idx_audit_log_actor_created_at (actor_user_id,created_at),
  KEY idx_audit_log_action_created_at (action_type,created_at)
);
CREATE TABLE class_analytics_daily_aggregate (
  id bigint NOT NULL AUTO_INCREMENT,
  teaching_class_id bigint NOT NULL,
  stat_date date NOT NULL,
  week_start_date date NOT NULL,
  source_type varchar(16) NOT NULL,
  aggregation_level varchar(16) NOT NULL,
  lexical_pair_id bigint NOT NULL DEFAULT '0',
  lexical_pair_type varchar(32) NOT NULL DEFAULT 'ALL',
  training_mode varchar(32) NOT NULL DEFAULT 'ALL',
  context_support_level varchar(16) NOT NULL DEFAULT 'ALL',
  attempt_count int NOT NULL DEFAULT '0',
  correct_count int NOT NULL DEFAULT '0',
  incorrect_count int NOT NULL DEFAULT '0',
  total_reaction_time_ms bigint NOT NULL DEFAULT '0',
  total_hesitation_time_ms bigint NOT NULL DEFAULT '0',
  positive_transfer_score_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  negative_transfer_risk_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  context_sensitivity_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  semantic_discrimination_sum decimal(14,4) NOT NULL DEFAULT '0.0000',
  high_risk_count int NOT NULL DEFAULT '0',
  pending_review_count int NOT NULL DEFAULT '0',
  completion_count int NOT NULL DEFAULT '0',
  false_friend_confusion_count int NOT NULL DEFAULT '0',
  context_ignored_count int NOT NULL DEFAULT '0',
  over_transfer_count int NOT NULL DEFAULT '0',
  under_transfer_count int NOT NULL DEFAULT '0',
  orthographic_interference_count int NOT NULL DEFAULT '0',
  semantic_misfire_count int NOT NULL DEFAULT '0',
  last_event_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_teaching_class_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then teaching_class_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_class_analytics_daily_aggregate (active_teaching_class_id,stat_date,source_type,aggregation_level,lexical_pair_id,lexical_pair_type,training_mode,context_support_level),
  KEY idx_class_analytics_daily_aggregate_class_date (teaching_class_id,stat_date),
  KEY idx_class_analytics_daily_aggregate_class_week (teaching_class_id,week_start_date)
);
CREATE TABLE diagnosis_item_result (
  id bigint NOT NULL AUTO_INCREMENT,
  session_id bigint NOT NULL,
  template_item_id bigint NOT NULL,
  lexical_pair_id bigint NOT NULL,
  task_type varchar(32) NOT NULL,
  presentation_order int NOT NULL,
  answer_state varchar(16) NOT NULL DEFAULT 'PENDING',
  stimulus_started_at timestamp NULL DEFAULT NULL,
  submitted_at timestamp NULL DEFAULT NULL,
  reaction_time_ms int DEFAULT NULL,
  hesitation_time_ms int DEFAULT NULL,
  selected_answer_key varchar(64) DEFAULT NULL,
  answer_payload_json longtext,
  is_correct tinyint(1) DEFAULT NULL,
  detected_error_type varchar(64) DEFAULT NULL,
  semantic_consistent tinyint(1) DEFAULT NULL,
  transfer_risk_score decimal(8,4) DEFAULT NULL,
  item_score decimal(8,4) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_diagnosis_item_result_session_item (session_id,template_item_id),
  KEY fk_diagnosis_item_result_template_item_id (template_item_id),
  KEY fk_diagnosis_item_result_lexical_pair_id (lexical_pair_id),
  KEY idx_diagnosis_item_result_session_order (session_id,presentation_order),
  KEY idx_diagnosis_item_result_session_state (session_id,answer_state)
);
CREATE TABLE diagnosis_session (
  id bigint NOT NULL AUTO_INCREMENT,
  template_id bigint NOT NULL,
  owner_user_id bigint NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'IN_PROGRESS',
  session_seed bigint NOT NULL,
  total_items int NOT NULL DEFAULT '0',
  answered_items int NOT NULL DEFAULT '0',
  current_item_order int DEFAULT NULL,
  last_saved_at timestamp NULL DEFAULT NULL,
  progress_snapshot_json longtext,
  started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_owner_user_id bigint GENERATED ALWAYS AS ((case when ((deleted = false) and (status = 'IN_PROGRESS')) then owner_user_id else NULL end)),
  completion_hooks_status varchar(16) DEFAULT NULL,
  completion_hooks_updated_at timestamp NULL DEFAULT NULL,
  completion_hooks_error varchar(512) DEFAULT NULL,
  launch_context_json longtext,
  PRIMARY KEY (id),
  UNIQUE KEY uk_diagnosis_session_active_owner (active_owner_user_id),
  KEY idx_diagnosis_session_owner_status (owner_user_id,status,started_at),
  KEY idx_diagnosis_session_template_status (template_id,status),
  KEY idx_diagnosis_session_status_last_saved_at (status,last_saved_at),
  KEY idx_diagnosis_session_completion_hooks_status (completion_hooks_status,completed_at)
);
CREATE TABLE diagnosis_summary (
  id bigint NOT NULL AUTO_INCREMENT,
  session_id bigint NOT NULL,
  owner_user_id bigint NOT NULL,
  template_id bigint NOT NULL,
  positive_transfer_score decimal(8,4) NOT NULL,
  negative_transfer_risk decimal(8,4) NOT NULL,
  context_sensitivity decimal(8,4) NOT NULL,
  semantic_discrimination decimal(8,4) NOT NULL,
  overall_accuracy decimal(8,4) NOT NULL,
  average_reaction_time_ms bigint NOT NULL,
  error_type_distribution_json longtext NOT NULL,
  high_risk_lexical_pairs_json longtext NOT NULL,
  chart_payload_json longtext NOT NULL,
  generated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scoring_version varchar(32) NOT NULL DEFAULT 'RULE_V1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_diagnosis_summary_session (session_id),
  KEY fk_diagnosis_summary_template_id (template_id),
  KEY idx_diagnosis_summary_owner_generated (owner_user_id,generated_at)
);
CREATE TABLE diagnosis_template (
  id bigint NOT NULL AUTO_INCREMENT,
  template_name varchar(128) NOT NULL,
  description varchar(500) DEFAULT NULL,
  owner_user_id bigint NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'DRAFT',
  estimated_duration_minutes int NOT NULL DEFAULT '10',
  scoring_version varchar(32) NOT NULL DEFAULT 'RULE_V1',
  item_count int NOT NULL DEFAULT '0',
  metadata_json text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  target_class_id bigint DEFAULT NULL,
  share_scope varchar(16) NOT NULL DEFAULT 'PRIVATE',
  PRIMARY KEY (id),
  KEY idx_diagnosis_template_owner_status (owner_user_id,status),
  KEY fk_diagnosis_template_target_class_id (target_class_id),
  KEY idx_diagnosis_template_status_target_class (status,target_class_id,updated_at),
  KEY idx_diagnosis_template_share_status_updated (share_scope,status,updated_at)
);
CREATE TABLE diagnosis_template_draft (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  source_template_id bigint DEFAULT NULL,
  published_template_id bigint DEFAULT NULL,
  template_name varchar(128) NOT NULL,
  description varchar(500) DEFAULT NULL,
  publish_target varchar(32) NOT NULL DEFAULT 'SELF',
  estimated_duration_minutes int NOT NULL DEFAULT '10',
  scoring_version varchar(32) NOT NULL DEFAULT 'RULE_V1',
  sync_state varchar(32) NOT NULL DEFAULT 'DIRTY',
  version bigint NOT NULL DEFAULT '1',
  schema_json longtext NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY fk_diagnosis_template_draft_source_template_id (source_template_id),
  KEY fk_diagnosis_template_draft_published_template_id (published_template_id),
  KEY idx_diagnosis_template_draft_owner_updated (owner_user_id,updated_at),
  KEY idx_diagnosis_template_draft_owner_source (owner_user_id,source_template_id,deleted)
);
CREATE TABLE diagnosis_template_item (
  id bigint NOT NULL AUTO_INCREMENT,
  template_id bigint NOT NULL,
  lexical_pair_id bigint NOT NULL,
  task_type varchar(32) NOT NULL,
  block_code varchar(64) NOT NULL,
  sort_order int NOT NULL DEFAULT '1',
  context_support_level varchar(16) NOT NULL,
  expected_semantic_match tinyint(1) NOT NULL,
  stimulus_payload_json longtext NOT NULL,
  options_payload_json longtext NOT NULL,
  correct_answer_key varchar(64) NOT NULL,
  scoring_profile_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY fk_diagnosis_template_item_lexical_pair_id (lexical_pair_id),
  KEY idx_diagnosis_template_item_template_order (template_id,block_code,sort_order)
);
CREATE TABLE idempotency_record (
  id bigint NOT NULL AUTO_INCREMENT,
  request_key varchar(128) NOT NULL,
  request_path varchar(255) NOT NULL,
  request_method varchar(16) NOT NULL,
  response_code varchar(32) NOT NULL,
  response_body text,
  expires_at timestamp NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  request_hash varchar(64) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_idempotency_request_key (request_key),
  KEY idx_idempotency_record_expires_at (expires_at)
);
CREATE TABLE intervention_record (
  id bigint NOT NULL AUTO_INCREMENT,
  teacher_user_id bigint NOT NULL,
  teaching_class_id bigint DEFAULT NULL,
  student_user_id bigint DEFAULT NULL,
  intervention_type varchar(64) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  priority varchar(16) NOT NULL DEFAULT 'NORMAL',
  trigger_source varchar(32) NOT NULL,
  trigger_snapshot_json longtext,
  baseline_snapshot_id bigint DEFAULT NULL,
  completion_snapshot_id bigint DEFAULT NULL,
  note varchar(1000) DEFAULT NULL,
  planned_at timestamp NULL DEFAULT NULL,
  completed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY fk_intervention_record_class_id (teaching_class_id),
  KEY idx_intervention_record_teacher_status_priority (teacher_user_id,status,priority,planned_at),
  KEY fk_intervention_record_baseline_snapshot (baseline_snapshot_id),
  KEY fk_intervention_record_completion_snapshot (completion_snapshot_id),
  KEY idx_intervention_record_student_snapshots (student_user_id,baseline_snapshot_id,completion_snapshot_id)
);
CREATE TABLE learning_profile_snapshot (
  id bigint NOT NULL AUTO_INCREMENT,
  scope varchar(16) NOT NULL,
  student_user_id bigint DEFAULT NULL,
  teaching_class_id bigint DEFAULT NULL,
  teacher_user_id bigint DEFAULT NULL,
  last_diagnosis_summary_id bigint DEFAULT NULL,
  last_training_session_id bigint DEFAULT NULL,
  primary_risk_level varchar(16) NOT NULL,
  recommended_training_mode varchar(32) NOT NULL,
  pending_review_count int NOT NULL DEFAULT '0',
  high_risk_pair_count int NOT NULL DEFAULT '0',
  recent_accuracy decimal(8,4) NOT NULL DEFAULT '0.0000',
  recent_negative_transfer_risk decimal(8,4) NOT NULL DEFAULT '0.0000',
  recent_avg_reaction_time_ms bigint NOT NULL DEFAULT '0',
  last_active_at timestamp NULL DEFAULT NULL,
  snapshot_json longtext NOT NULL,
  snapshot_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version int NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_student_user_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then student_user_id else NULL end)),
  active_teaching_class_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then teaching_class_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_learning_profile_snapshot_scope_student (scope,active_student_user_id),
  UNIQUE KEY uk_learning_profile_snapshot_scope_class (scope,active_teaching_class_id),
  KEY fk_learning_profile_snapshot_student_user_id (student_user_id),
  KEY fk_learning_profile_snapshot_class_id (teaching_class_id),
  KEY fk_learning_profile_snapshot_teacher_user_id (teacher_user_id),
  KEY idx_learning_profile_snapshot_student (scope,student_user_id,snapshot_at),
  KEY idx_learning_profile_snapshot_class (scope,teaching_class_id,snapshot_at)
);
CREATE TABLE lexical_import_batch (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  original_filename varchar(255) NOT NULL,
  content_type varchar(255) DEFAULT NULL,
  file_size_bytes bigint NOT NULL,
  source_format varchar(16) NOT NULL,
  status varchar(32) NOT NULL,
  total_rows int NOT NULL DEFAULT '0',
  ready_rows int NOT NULL DEFAULT '0',
  invalid_rows int NOT NULL DEFAULT '0',
  skipped_rows int NOT NULL DEFAULT '0',
  imported_rows int NOT NULL DEFAULT '0',
  error_message text,
  parser_job_started_at timestamp NULL DEFAULT NULL,
  parser_job_finished_at timestamp NULL DEFAULT NULL,
  import_job_started_at timestamp NULL DEFAULT NULL,
  import_job_finished_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_lexical_import_batch_owner_status_created (owner_user_id,status,created_at),
  KEY idx_lexical_import_batch_status_created (status,created_at)
);
CREATE TABLE lexical_import_file (
  id bigint NOT NULL AUTO_INCREMENT,
  batch_id bigint NOT NULL,
  original_filename varchar(255) NOT NULL,
  content_type varchar(255) DEFAULT NULL,
  file_size_bytes bigint NOT NULL,
  sha256 varchar(64) NOT NULL,
  file_content longblob NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_batch_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then batch_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lexical_import_file_batch (active_batch_id),
  KEY idx_lexical_import_file_batch_id (batch_id)
);
CREATE TABLE lexical_import_row (
  id bigint NOT NULL AUTO_INCREMENT,
  batch_id bigint NOT NULL,
  import_row_number int NOT NULL,
  row_status varchar(32) NOT NULL,
  draft_json longtext NOT NULL,
  validation_errors_json longtext,
  imported_lexical_pair_id bigint DEFAULT NULL,
  import_message text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_batch_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then batch_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lexical_import_row_batch_row (active_batch_id,import_row_number),
  KEY fk_lexical_import_row_pair_id (imported_lexical_pair_id),
  KEY idx_lexical_import_row_batch_status_row (batch_id,row_status,import_row_number)
);
CREATE TABLE lexical_list (
  id bigint NOT NULL AUTO_INCREMENT,
  list_name varchar(128) NOT NULL,
  description varchar(255) DEFAULT NULL,
  owner_user_id bigint NOT NULL,
  active tinyint(1) NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_lexical_list_owner_user_id (owner_user_id,active)
);
CREATE TABLE lexical_list_item (
  id bigint NOT NULL AUTO_INCREMENT,
  lexical_list_id bigint NOT NULL,
  lexical_pair_id bigint NOT NULL,
  sort_order int NOT NULL DEFAULT '1',
  notes varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_lexical_list_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then lexical_list_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lexical_list_item (active_lexical_list_id,lexical_pair_id),
  KEY fk_lexical_list_item_pair_id (lexical_pair_id),
  KEY idx_lexical_list_item_list_id (lexical_list_id,sort_order)
);
CREATE TABLE lexical_pair (
  id bigint NOT NULL AUTO_INCREMENT,
  english_word varchar(128) NOT NULL,
  french_word varchar(128) NOT NULL,
  chinese_gloss varchar(255) NOT NULL,
  lexical_pair_type varchar(32) NOT NULL,
  semantic_overlap_score decimal(5,4) NOT NULL,
  false_friend_risk decimal(5,4) NOT NULL,
  default_context_support varchar(16) NOT NULL,
  difficulty_level int NOT NULL,
  notes text,
  source varchar(255) DEFAULT NULL,
  source_code varchar(64) DEFAULT NULL,
  content_version varchar(64) DEFAULT NULL,
  word_id varchar(128) DEFAULT NULL,
  searchable_text text NOT NULL,
  search_pinyin varchar(1024) DEFAULT NULL,
  search_initials varchar(1024) DEFAULT NULL,
  knowledge_status varchar(32) NOT NULL DEFAULT 'DRAFT',
  embedding_status varchar(32) NOT NULL DEFAULT 'PENDING',
  last_embedded_at timestamp NULL DEFAULT NULL,
  active tinyint(1) NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_english_word varchar(128) GENERATED ALWAYS AS ((case when (deleted = false) then english_word else NULL end)),
  active_source_code varchar(64) GENERATED ALWAYS AS ((case when (deleted = false) then source_code else NULL end)),
  active_content_version varchar(64) GENERATED ALWAYS AS ((case when (deleted = false) then content_version else NULL end)),
  active_word_id varchar(128) GENERATED ALWAYS AS ((case when (deleted = false) then word_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lexical_pair_word_pair (active_english_word,french_word),
  UNIQUE KEY uk_lexical_pair_source_version_word (active_source_code,active_content_version,active_word_id),
  KEY idx_lexical_pair_type_active (lexical_pair_type,active),
  KEY idx_lexical_pair_context_active (default_context_support,active),
  KEY idx_lexical_pair_risk (false_friend_risk),
  KEY idx_lexical_pair_knowledge_embedding (knowledge_status,embedding_status),
  KEY idx_lexical_pair_english_word (english_word),
  KEY idx_lexical_pair_french_word (french_word),
  KEY idx_lexical_pair_chinese_gloss (chinese_gloss)
);
CREATE TABLE lexical_pair_example (
  id bigint NOT NULL AUTO_INCREMENT,
  lexical_pair_sense_id bigint NOT NULL,
  sort_order int NOT NULL DEFAULT '1',
  english_example varchar(1000) DEFAULT NULL,
  french_example varchar(1000) DEFAULT NULL,
  chinese_translation varchar(1000) DEFAULT NULL,
  context_support_level varchar(16) NOT NULL,
  source varchar(255) DEFAULT NULL,
  searchable_text text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_lexical_pair_example_sense_id (lexical_pair_sense_id,sort_order)
);
CREATE TABLE lexical_pair_sense (
  id bigint NOT NULL AUTO_INCREMENT,
  lexical_pair_id bigint NOT NULL,
  sort_order int NOT NULL DEFAULT '1',
  english_definition varchar(500) DEFAULT NULL,
  french_definition varchar(500) DEFAULT NULL,
  chinese_definition varchar(500) DEFAULT NULL,
  searchable_text text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_lexical_pair_sense_pair_id (lexical_pair_id,sort_order)
);
CREATE TABLE lexical_pair_tag_rel (
  id bigint NOT NULL AUTO_INCREMENT,
  lexical_pair_id bigint NOT NULL,
  lexical_tag_id bigint NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_lexical_pair_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then lexical_pair_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lexical_pair_tag_rel (active_lexical_pair_id,lexical_tag_id),
  KEY fk_lexical_pair_tag_rel_tag_id (lexical_tag_id),
  KEY idx_lexical_pair_tag_rel_pair_id (lexical_pair_id)
);
CREATE TABLE lexical_tag (
  id bigint NOT NULL AUTO_INCREMENT,
  tag_name varchar(64) NOT NULL,
  description varchar(255) DEFAULT NULL,
  active tinyint(1) NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_tag_name varchar(64) GENERATED ALWAYS AS ((case when (deleted = false) then tag_name else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_lexical_tag_name (active_tag_name)
);
CREATE TABLE notification (
  id bigint NOT NULL AUTO_INCREMENT,
  recipient_user_id bigint NOT NULL,
  category varchar(64) NOT NULL,
  level varchar(32) NOT NULL,
  title varchar(160) NOT NULL,
  content text NOT NULL,
  action_url varchar(255) DEFAULT NULL,
  action_label varchar(64) DEFAULT NULL,
  status varchar(32) NOT NULL DEFAULT 'UNREAD',
  read_at timestamp NULL DEFAULT NULL,
  payload_json text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_notification_recipient_created (recipient_user_id,created_at DESC,id DESC),
  KEY idx_notification_recipient_status (recipient_user_id,status,created_at DESC,id DESC)
);
CREATE TABLE platform_event_outbox (
  id bigint NOT NULL AUTO_INCREMENT,
  event_id varchar(128) NOT NULL,
  event_type varchar(128) NOT NULL,
  exchange_name varchar(128) NOT NULL,
  routing_key varchar(255) NOT NULL,
  payload_json longtext NOT NULL,
  headers_json longtext,
  trace_id varchar(128) DEFAULT NULL,
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  attempt_count int NOT NULL DEFAULT '0',
  next_attempt_at datetime DEFAULT CURRENT_TIMESTAMP,
  last_error varchar(1000) DEFAULT NULL,
  processing_started_at datetime DEFAULT NULL,
  published_at datetime DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint NOT NULL DEFAULT '0',
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint NOT NULL DEFAULT '0',
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_platform_event_outbox_event_id (event_id),
  KEY idx_platform_event_outbox_status_due (status,next_attempt_at,id),
  KEY idx_platform_event_outbox_processing_started (status,processing_started_at,id),
  KEY idx_platform_event_outbox_type_status (event_type,status,updated_at)
);
CREATE TABLE platform_event_outbox_dlq (
  outbox_id bigint NOT NULL,
  event_id varchar(128) NOT NULL,
  event_type varchar(128) NOT NULL,
  exchange_name varchar(128) NOT NULL,
  routing_key varchar(255) NOT NULL,
  payload_json longtext NOT NULL,
  headers_json longtext,
  trace_id varchar(128) DEFAULT NULL,
  attempt_count int NOT NULL DEFAULT '0',
  next_attempt_at datetime DEFAULT NULL,
  last_error varchar(1000) DEFAULT NULL,
  processing_started_at datetime DEFAULT NULL,
  published_at datetime DEFAULT NULL,
  created_at datetime NOT NULL,
  updated_at datetime NOT NULL,
  exhausted_at datetime NOT NULL,
  PRIMARY KEY (outbox_id),
  UNIQUE KEY uk_platform_event_outbox_dlq_event_id (event_id),
  KEY idx_platform_event_outbox_dlq_event_type (event_type,updated_at),
  KEY idx_platform_event_outbox_dlq_exhausted_at (exhausted_at,outbox_id)
);
CREATE TABLE review_schedule (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  lexical_pair_id bigint NOT NULL,
  wrong_book_id bigint NOT NULL,
  source_training_session_id bigint DEFAULT NULL,
  schedule_stage int NOT NULL,
  interval_days int NOT NULL,
  due_at timestamp NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  review_mode varchar(32) NOT NULL,
  trigger_reason varchar(255) NOT NULL,
  completed_at timestamp NULL DEFAULT NULL,
  snapshot_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY fk_review_schedule_lexical_pair_id (lexical_pair_id),
  KEY fk_review_schedule_wrong_book_id (wrong_book_id),
  KEY fk_review_schedule_source_training_session_id (source_training_session_id),
  KEY idx_review_schedule_owner_due (owner_user_id,status,due_at)
);
CREATE TABLE student_profile (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  student_no varchar(64) NOT NULL,
  grade_name varchar(64) NOT NULL,
  english_level varchar(16) NOT NULL,
  french_level varchar(16) NOT NULL,
  composite_score int NOT NULL,
  daily_training_target int DEFAULT NULL,
  weekly_accuracy_target int DEFAULT NULL,
  learning_goals_updated_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  learning_profile_snapshot_json longtext,
  learning_profile_updated_at timestamp NULL DEFAULT NULL,
  course_stage varchar(64) NOT NULL DEFAULT 'FOUNDATION',
  PRIMARY KEY (id),
  UNIQUE KEY uk_student_profile_user_id (user_id),
  UNIQUE KEY uk_student_profile_student_no (student_no)
);
CREATE TABLE teacher_profile (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  employee_no varchar(64) NOT NULL,
  department varchar(128) NOT NULL,
  title varchar(128) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_teacher_profile_user_id (user_id),
  UNIQUE KEY uk_teacher_profile_employee_no (employee_no)
);
CREATE TABLE teaching_class (
  id bigint NOT NULL AUTO_INCREMENT,
  class_code varchar(64) NOT NULL,
  class_name varchar(128) NOT NULL,
  grade_name varchar(64) NOT NULL,
  teacher_user_id bigint NOT NULL,
  active tinyint(1) NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_teaching_class_code (class_code),
  KEY idx_teaching_class_teacher_active (teacher_user_id,active)
);
CREATE TABLE teaching_class_student (
  id bigint NOT NULL AUTO_INCREMENT,
  teaching_class_id bigint NOT NULL,
  student_user_id bigint NOT NULL,
  joined_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  left_at timestamp NULL DEFAULT NULL,
  active tinyint(1) NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_student_user_id bigint GENERATED ALWAYS AS ((case when ((deleted = false) and (active = true)) then student_user_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_teaching_class_student (teaching_class_id,active_student_user_id),
  KEY idx_teaching_class_student_class_active (teaching_class_id,active),
  KEY idx_teaching_class_student_student_active (student_user_id,active)
);
CREATE TABLE training_item_result (
  id bigint NOT NULL AUTO_INCREMENT,
  session_id bigint NOT NULL,
  plan_item_id bigint NOT NULL,
  lexical_pair_id bigint NOT NULL,
  mode varchar(32) NOT NULL,
  item_type varchar(32) NOT NULL,
  presentation_order int NOT NULL,
  answer_state varchar(16) NOT NULL DEFAULT 'PENDING',
  cognitive_tag varchar(16) NOT NULL,
  stimulus_json longtext NOT NULL,
  options_json longtext NOT NULL,
  correct_answer_key varchar(64) NOT NULL,
  selected_answer_key varchar(64) DEFAULT NULL,
  answer_payload_json longtext,
  submitted_at timestamp NULL DEFAULT NULL,
  reaction_time_ms int DEFAULT NULL,
  hesitation_time_ms int DEFAULT NULL,
  is_correct tinyint(1) DEFAULT NULL,
  detected_error_type varchar(64) DEFAULT NULL,
  review_required tinyint(1) NOT NULL DEFAULT '0',
  adaptation_action varchar(64) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_training_item_result_session_order (session_id,presentation_order),
  KEY fk_training_item_result_plan_item_id (plan_item_id),
  KEY fk_training_item_result_lexical_pair_id (lexical_pair_id),
  KEY idx_training_item_result_session_order (session_id,presentation_order),
  KEY idx_training_item_result_session_state (session_id,answer_state)
);
CREATE TABLE training_plan (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  source_diagnosis_session_id bigint NOT NULL,
  source_diagnosis_summary_id bigint NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'GENERATED',
  priority_mode varchar(32) NOT NULL,
  recommended_difficulty int NOT NULL,
  risk_level varchar(16) NOT NULL,
  estimated_training_volume int NOT NULL,
  recommendation_reason varchar(1000) NOT NULL,
  target_metrics_json longtext NOT NULL,
  generated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at timestamp NULL DEFAULT NULL,
  completed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_owner_user_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then owner_user_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_training_plan_owner_summary (active_owner_user_id,source_diagnosis_summary_id),
  KEY fk_training_plan_source_diagnosis_session_id (source_diagnosis_session_id),
  KEY fk_training_plan_source_diagnosis_summary_id (source_diagnosis_summary_id),
  KEY idx_training_plan_owner_generated (owner_user_id,generated_at),
  KEY idx_training_plan_status (owner_user_id,status,generated_at)
);
CREATE TABLE training_plan_item (
  id bigint NOT NULL AUTO_INCREMENT,
  plan_id bigint NOT NULL,
  lexical_pair_id bigint NOT NULL,
  recommended_mode varchar(32) NOT NULL,
  recommended_difficulty int NOT NULL,
  risk_level varchar(16) NOT NULL,
  priority_score decimal(10,4) NOT NULL,
  recommended_reason varchar(1000) NOT NULL,
  dominant_error_type varchar(64) DEFAULT NULL,
  target_context_support varchar(16) DEFAULT NULL,
  expected_exposures int NOT NULL DEFAULT '3',
  sort_order int NOT NULL DEFAULT '1',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  KEY idx_training_plan_item_plan_order (plan_id,recommended_mode,sort_order),
  KEY idx_training_plan_item_lexical_pair_id (lexical_pair_id)
);
CREATE TABLE training_session (
  id bigint NOT NULL AUTO_INCREMENT,
  plan_id bigint NOT NULL,
  owner_user_id bigint NOT NULL,
  mode varchar(32) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'IN_PROGRESS',
  session_seed bigint NOT NULL,
  total_items int NOT NULL DEFAULT '0',
  answered_items int NOT NULL DEFAULT '0',
  current_item_order int DEFAULT NULL,
  planned_difficulty int NOT NULL,
  risk_level varchar(16) NOT NULL,
  progress_snapshot_json longtext,
  summary_snapshot_json longtext,
  started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  last_saved_at timestamp NULL DEFAULT NULL,
  launch_context_json longtext,
  active_owner_user_id bigint GENERATED ALWAYS AS ((case when ((deleted = false) and (status = 'IN_PROGRESS')) then owner_user_id else NULL end)),
  completion_hooks_status varchar(16) DEFAULT NULL,
  completion_hooks_updated_at timestamp NULL DEFAULT NULL,
  completion_hooks_error varchar(512) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_training_session_active_owner (active_owner_user_id),
  KEY fk_training_session_plan_id (plan_id),
  KEY idx_training_session_owner_status (owner_user_id,status,started_at),
  KEY idx_training_session_status_last_saved_at (status,last_saved_at),
  KEY idx_training_session_completion_hooks_status (completion_hooks_status,completed_at)
);
CREATE TABLE user_role (
  id bigint NOT NULL AUTO_INCREMENT,
  user_id bigint NOT NULL,
  role_code varchar(32) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_role_user_id_role_code (user_id,role_code),
  KEY idx_user_role_user_id (user_id)
);
CREATE TABLE users (
  id bigint NOT NULL AUTO_INCREMENT,
  username varchar(64) NOT NULL,
  email varchar(128) NOT NULL,
  password_hash varchar(255) NOT NULL,
  display_name varchar(128) NOT NULL,
  enabled tinyint(1) NOT NULL DEFAULT '1',
  last_login_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_username (username),
  UNIQUE KEY uk_users_email (email),
  KEY idx_users_username (username),
  KEY idx_users_email (email)
);
CREATE TABLE wrong_book (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  lexical_pair_id bigint NOT NULL,
  source_training_session_id bigint DEFAULT NULL,
  source_item_result_id bigint DEFAULT NULL,
  wrong_count int NOT NULL DEFAULT '1',
  first_wrong_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_wrong_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_error_type varchar(64) DEFAULT NULL,
  mastery_status varchar(32) NOT NULL DEFAULT 'REVIEWING',
  next_review_at timestamp NULL DEFAULT NULL,
  latest_snapshot_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_owner_user_id bigint GENERATED ALWAYS AS ((case when (deleted = false) then owner_user_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_wrong_book_owner_pair (active_owner_user_id,lexical_pair_id),
  KEY fk_wrong_book_lexical_pair_id (lexical_pair_id),
  KEY fk_wrong_book_source_training_session_id (source_training_session_id),
  KEY fk_wrong_book_source_item_result_id (source_item_result_id),
  KEY idx_wrong_book_owner_next_review (owner_user_id,next_review_at)
);
CREATE TABLE practice_session (
  id bigint NOT NULL AUTO_INCREMENT,
  owner_user_id bigint NOT NULL,
  bank_code varchar(64) NOT NULL,
  section_code varchar(64) DEFAULT NULL,
  status varchar(32) NOT NULL DEFAULT 'IN_PROGRESS',
  total_count int NOT NULL DEFAULT '0',
  answered_count int NOT NULL DEFAULT '0',
  correct_count int NOT NULL DEFAULT '0',
  started_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp NULL DEFAULT NULL,
  tutoring_status varchar(16) DEFAULT NULL,
  tutoring_json longtext,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  active_owner_user_id bigint GENERATED ALWAYS AS ((case when ((deleted = false) and (status = 'IN_PROGRESS')) then owner_user_id else NULL end)),
  PRIMARY KEY (id),
  UNIQUE KEY uk_practice_session_active_owner (active_owner_user_id),
  KEY idx_practice_session_owner_status (owner_user_id,status,started_at)
);
CREATE TABLE practice_session_answer (
  id bigint NOT NULL AUTO_INCREMENT,
  session_id bigint NOT NULL,
  question_order int NOT NULL,
  question_version_id bigint NOT NULL,
  question_code varchar(64) NOT NULL,
  question_type varchar(32) NOT NULL,
  section_code varchar(64) NOT NULL,
  construct_code varchar(64) DEFAULT NULL,
  transfer_category varchar(32) DEFAULT NULL,
  target_word varchar(255) DEFAULT NULL,
  stem_text_snapshot text,
  prompt_text_snapshot text,
  options_json_snapshot longtext,
  correct_answer_json longtext NOT NULL,
  explanation_text_snapshot text,
  option_explanations_json longtext,
  response_json longtext,
  is_correct tinyint(1) DEFAULT NULL,
  wrong_attempt_count int NOT NULL DEFAULT '0',
  spelling_hint_shown tinyint(1) NOT NULL DEFAULT '0',
  answered_at timestamp NULL DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint DEFAULT NULL,
  deleted tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_practice_session_answer_order (session_id,question_order),
  KEY idx_practice_session_answer_session (session_id)
);


ALTER TABLE account_action_token ADD CONSTRAINT fk_account_action_token_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE achievement ADD CONSTRAINT fk_achievement_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE ai_conversation_message ADD CONSTRAINT fk_ai_conversation_message_session_id FOREIGN KEY (conversation_session_id) REFERENCES ai_conversation_session (id);
ALTER TABLE ai_conversation_session ADD CONSTRAINT fk_ai_conversation_session_student_user_id FOREIGN KEY (student_user_id) REFERENCES users (id);
ALTER TABLE ai_generation_record ADD CONSTRAINT fk_ai_generation_record_class_id FOREIGN KEY (teaching_class_id) REFERENCES teaching_class (id);
ALTER TABLE ai_generation_record ADD CONSTRAINT fk_ai_generation_record_diagnosis_summary_id FOREIGN KEY (diagnosis_summary_id) REFERENCES diagnosis_summary (id);
ALTER TABLE ai_generation_record ADD CONSTRAINT fk_ai_generation_record_intervention_record_id FOREIGN KEY (intervention_record_id) REFERENCES intervention_record (id);
ALTER TABLE ai_generation_record ADD CONSTRAINT fk_ai_generation_record_practice_session_id FOREIGN KEY (practice_session_id) REFERENCES practice_session (id);
ALTER TABLE ai_generation_record ADD CONSTRAINT fk_ai_generation_record_student_user_id FOREIGN KEY (student_user_id) REFERENCES users (id);
ALTER TABLE ai_generation_record ADD CONSTRAINT fk_ai_generation_record_teacher_user_id FOREIGN KEY (teacher_user_id) REFERENCES users (id);
ALTER TABLE ai_generation_record ADD CONSTRAINT fk_ai_generation_record_training_session_id FOREIGN KEY (training_session_id) REFERENCES training_session (id);
ALTER TABLE analytics_daily_aggregate ADD CONSTRAINT fk_analytics_daily_aggregate_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE assessment_attempt ADD CONSTRAINT fk_assessment_attempt_paper_id FOREIGN KEY (paper_id) REFERENCES assessment_paper (id);
ALTER TABLE assessment_attempt ADD CONSTRAINT fk_assessment_attempt_publish_id FOREIGN KEY (publish_id) REFERENCES assessment_publish (id);
ALTER TABLE assessment_attempt ADD CONSTRAINT fk_assessment_attempt_student_user_id FOREIGN KEY (student_user_id) REFERENCES users (id);
ALTER TABLE assessment_attempt_answer ADD CONSTRAINT fk_assessment_attempt_answer_attempt_id FOREIGN KEY (attempt_id) REFERENCES assessment_attempt (id);
ALTER TABLE assessment_attempt_answer ADD CONSTRAINT fk_assessment_attempt_answer_question_id FOREIGN KEY (question_id) REFERENCES assessment_question (id);
ALTER TABLE assessment_paper ADD CONSTRAINT fk_assessment_paper_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE assessment_publish ADD CONSTRAINT fk_assessment_publish_class_id FOREIGN KEY (teaching_class_id) REFERENCES teaching_class (id);
ALTER TABLE assessment_publish ADD CONSTRAINT fk_assessment_publish_paper_id FOREIGN KEY (paper_id) REFERENCES assessment_paper (id);
ALTER TABLE assessment_publish ADD CONSTRAINT fk_assessment_publish_published_by FOREIGN KEY (published_by) REFERENCES users (id);
ALTER TABLE assessment_publish_recipient ADD CONSTRAINT fk_assessment_publish_recipient_class_id FOREIGN KEY (teaching_class_id) REFERENCES teaching_class (id);
ALTER TABLE assessment_publish_recipient ADD CONSTRAINT fk_assessment_publish_recipient_paper_id FOREIGN KEY (paper_id) REFERENCES assessment_paper (id);
ALTER TABLE assessment_publish_recipient ADD CONSTRAINT fk_assessment_publish_recipient_publish_id FOREIGN KEY (publish_id) REFERENCES assessment_publish (id);
ALTER TABLE assessment_publish_recipient ADD CONSTRAINT fk_assessment_publish_recipient_student_user_id FOREIGN KEY (student_user_id) REFERENCES users (id);
ALTER TABLE assessment_question ADD CONSTRAINT fk_assessment_question_paper_id FOREIGN KEY (paper_id) REFERENCES assessment_paper (id);
ALTER TABLE assessment_question_bank ADD CONSTRAINT fk_assessment_question_bank_owner FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE assessment_question_version ADD CONSTRAINT fk_assessment_question_version_bank FOREIGN KEY (question_bank_id) REFERENCES assessment_question_bank (id);
ALTER TABLE assessment_questionnaire ADD CONSTRAINT fk_assessment_questionnaire_owner FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE assessment_questionnaire_version ADD CONSTRAINT fk_assessment_questionnaire_version_questionnaire FOREIGN KEY (questionnaire_id) REFERENCES assessment_questionnaire (id);
ALTER TABLE assessment_questionnaire_version ADD CONSTRAINT fk_assessment_questionnaire_version_paper FOREIGN KEY (paper_id) REFERENCES assessment_paper (id);
ALTER TABLE assessment_questionnaire_section ADD CONSTRAINT fk_assessment_questionnaire_section_version FOREIGN KEY (questionnaire_version_id) REFERENCES assessment_questionnaire_version (id);
ALTER TABLE assessment_questionnaire_item ADD CONSTRAINT fk_assessment_questionnaire_item_version FOREIGN KEY (questionnaire_version_id) REFERENCES assessment_questionnaire_version (id);
ALTER TABLE assessment_questionnaire_item ADD CONSTRAINT fk_assessment_questionnaire_item_section FOREIGN KEY (section_id) REFERENCES assessment_questionnaire_section (id);
ALTER TABLE assessment_questionnaire_item ADD CONSTRAINT fk_assessment_questionnaire_item_question FOREIGN KEY (assessment_question_id) REFERENCES assessment_question (id);
ALTER TABLE assessment_questionnaire_item ADD CONSTRAINT fk_assessment_questionnaire_item_qversion FOREIGN KEY (question_version_id) REFERENCES assessment_question_version (id);
ALTER TABLE assessment_public_release ADD CONSTRAINT fk_assessment_public_release_publish FOREIGN KEY (publish_id) REFERENCES assessment_publish (id);
ALTER TABLE assessment_participation_code ADD CONSTRAINT fk_assessment_participation_code_release FOREIGN KEY (public_release_id) REFERENCES assessment_public_release (id);
ALTER TABLE assessment_participant ADD CONSTRAINT fk_assessment_participant_publish FOREIGN KEY (publish_id) REFERENCES assessment_publish (id);
ALTER TABLE assessment_participant ADD CONSTRAINT fk_assessment_participant_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE assessment_participant ADD CONSTRAINT fk_assessment_participant_code FOREIGN KEY (participation_code_id) REFERENCES assessment_participation_code (id);
ALTER TABLE assessment_participant ADD CONSTRAINT fk_assessment_participant_attempt FOREIGN KEY (attempt_id) REFERENCES assessment_attempt (id);
ALTER TABLE assessment_participant_access ADD CONSTRAINT fk_assessment_participant_access_release FOREIGN KEY (public_release_id) REFERENCES assessment_public_release (id);
ALTER TABLE assessment_participant_access ADD CONSTRAINT fk_assessment_participant_access_participant FOREIGN KEY (participant_id) REFERENCES assessment_participant (id);
ALTER TABLE assessment_participant_access ADD CONSTRAINT fk_assessment_participant_access_code FOREIGN KEY (participation_code_id) REFERENCES assessment_participation_code (id);
ALTER TABLE assessment_participant_session ADD CONSTRAINT fk_assessment_participant_session_participant FOREIGN KEY (participant_id) REFERENCES assessment_participant (id);
ALTER TABLE assessment_question_bank_import ADD CONSTRAINT fk_assessment_question_bank_import_bank FOREIGN KEY (question_bank_id) REFERENCES assessment_question_bank (id);
ALTER TABLE assessment_question_bank_import ADD CONSTRAINT fk_assessment_question_bank_import_confirmed FOREIGN KEY (confirmed_by) REFERENCES users (id);
ALTER TABLE assessment_question_bank_import ADD CONSTRAINT fk_assessment_question_bank_import_committed FOREIGN KEY (committed_by) REFERENCES users (id);
ALTER TABLE assessment_content_review_issue ADD CONSTRAINT fk_assessment_content_review_issue_import FOREIGN KEY (import_id) REFERENCES assessment_question_bank_import (id);
ALTER TABLE assessment_content_review_issue ADD CONSTRAINT fk_assessment_content_review_issue_question FOREIGN KEY (question_version_id) REFERENCES assessment_question_version (id);
ALTER TABLE assessment_content_review_issue ADD CONSTRAINT fk_assessment_content_review_issue_resolver FOREIGN KEY (resolved_by) REFERENCES users (id);
ALTER TABLE assessment_timing_event ADD CONSTRAINT fk_assessment_timing_event_attempt FOREIGN KEY (attempt_id) REFERENCES assessment_attempt (id);
ALTER TABLE assessment_timing_event ADD CONSTRAINT fk_assessment_timing_event_question FOREIGN KEY (question_id) REFERENCES assessment_question (id);
ALTER TABLE assessment_metric_snapshot ADD CONSTRAINT fk_assessment_metric_snapshot_attempt FOREIGN KEY (attempt_id) REFERENCES assessment_attempt (id);
ALTER TABLE assessment_ai_analysis ADD CONSTRAINT fk_assessment_ai_analysis_attempt FOREIGN KEY (attempt_id) REFERENCES assessment_attempt (id);
ALTER TABLE assessment_ai_analysis ADD CONSTRAINT fk_assessment_ai_analysis_metric FOREIGN KEY (metric_snapshot_id) REFERENCES assessment_metric_snapshot (id);
ALTER TABLE assessment_ai_analysis ADD CONSTRAINT fk_assessment_ai_analysis_generation FOREIGN KEY (generation_record_id) REFERENCES ai_generation_record (id);
ALTER TABLE class_analytics_daily_aggregate ADD CONSTRAINT fk_class_analytics_daily_aggregate_class_id FOREIGN KEY (teaching_class_id) REFERENCES teaching_class (id);
ALTER TABLE diagnosis_item_result ADD CONSTRAINT fk_diagnosis_item_result_lexical_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE diagnosis_item_result ADD CONSTRAINT fk_diagnosis_item_result_session_id FOREIGN KEY (session_id) REFERENCES diagnosis_session (id);
ALTER TABLE diagnosis_item_result ADD CONSTRAINT fk_diagnosis_item_result_template_item_id FOREIGN KEY (template_item_id) REFERENCES diagnosis_template_item (id);
ALTER TABLE diagnosis_session ADD CONSTRAINT fk_diagnosis_session_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE diagnosis_session ADD CONSTRAINT fk_diagnosis_session_template_id FOREIGN KEY (template_id) REFERENCES diagnosis_template (id);
ALTER TABLE diagnosis_summary ADD CONSTRAINT fk_diagnosis_summary_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE diagnosis_summary ADD CONSTRAINT fk_diagnosis_summary_session_id FOREIGN KEY (session_id) REFERENCES diagnosis_session (id);
ALTER TABLE diagnosis_summary ADD CONSTRAINT fk_diagnosis_summary_template_id FOREIGN KEY (template_id) REFERENCES diagnosis_template (id);
ALTER TABLE diagnosis_template ADD CONSTRAINT fk_diagnosis_template_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE diagnosis_template ADD CONSTRAINT fk_diagnosis_template_target_class_id FOREIGN KEY (target_class_id) REFERENCES teaching_class (id);
ALTER TABLE diagnosis_template_draft ADD CONSTRAINT fk_diagnosis_template_draft_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE diagnosis_template_draft ADD CONSTRAINT fk_diagnosis_template_draft_published_template_id FOREIGN KEY (published_template_id) REFERENCES diagnosis_template (id);
ALTER TABLE diagnosis_template_draft ADD CONSTRAINT fk_diagnosis_template_draft_source_template_id FOREIGN KEY (source_template_id) REFERENCES diagnosis_template (id);
ALTER TABLE diagnosis_template_item ADD CONSTRAINT fk_diagnosis_template_item_lexical_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE diagnosis_template_item ADD CONSTRAINT fk_diagnosis_template_item_template_id FOREIGN KEY (template_id) REFERENCES diagnosis_template (id);
ALTER TABLE intervention_record ADD CONSTRAINT fk_intervention_record_baseline_snapshot FOREIGN KEY (baseline_snapshot_id) REFERENCES learning_profile_snapshot (id);
ALTER TABLE intervention_record ADD CONSTRAINT fk_intervention_record_class_id FOREIGN KEY (teaching_class_id) REFERENCES teaching_class (id);
ALTER TABLE intervention_record ADD CONSTRAINT fk_intervention_record_completion_snapshot FOREIGN KEY (completion_snapshot_id) REFERENCES learning_profile_snapshot (id);
ALTER TABLE intervention_record ADD CONSTRAINT fk_intervention_record_student_user_id FOREIGN KEY (student_user_id) REFERENCES users (id);
ALTER TABLE intervention_record ADD CONSTRAINT fk_intervention_record_teacher_user_id FOREIGN KEY (teacher_user_id) REFERENCES users (id);
ALTER TABLE learning_profile_snapshot ADD CONSTRAINT fk_learning_profile_snapshot_class_id FOREIGN KEY (teaching_class_id) REFERENCES teaching_class (id);
ALTER TABLE learning_profile_snapshot ADD CONSTRAINT fk_learning_profile_snapshot_student_user_id FOREIGN KEY (student_user_id) REFERENCES users (id);
ALTER TABLE learning_profile_snapshot ADD CONSTRAINT fk_learning_profile_snapshot_teacher_user_id FOREIGN KEY (teacher_user_id) REFERENCES users (id);
ALTER TABLE lexical_import_batch ADD CONSTRAINT fk_lexical_import_batch_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE lexical_import_file ADD CONSTRAINT fk_lexical_import_file_batch_id FOREIGN KEY (batch_id) REFERENCES lexical_import_batch (id);
ALTER TABLE lexical_import_row ADD CONSTRAINT fk_lexical_import_row_batch_id FOREIGN KEY (batch_id) REFERENCES lexical_import_batch (id);
ALTER TABLE lexical_import_row ADD CONSTRAINT fk_lexical_import_row_pair_id FOREIGN KEY (imported_lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE lexical_list ADD CONSTRAINT fk_lexical_list_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE lexical_list_item ADD CONSTRAINT fk_lexical_list_item_list_id FOREIGN KEY (lexical_list_id) REFERENCES lexical_list (id);
ALTER TABLE lexical_list_item ADD CONSTRAINT fk_lexical_list_item_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE lexical_pair_example ADD CONSTRAINT fk_lexical_pair_example_sense_id FOREIGN KEY (lexical_pair_sense_id) REFERENCES lexical_pair_sense (id);
ALTER TABLE lexical_pair_sense ADD CONSTRAINT fk_lexical_pair_sense_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE lexical_pair_tag_rel ADD CONSTRAINT fk_lexical_pair_tag_rel_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE lexical_pair_tag_rel ADD CONSTRAINT fk_lexical_pair_tag_rel_tag_id FOREIGN KEY (lexical_tag_id) REFERENCES lexical_tag (id);
ALTER TABLE notification ADD CONSTRAINT fk_notification_recipient_user_id FOREIGN KEY (recipient_user_id) REFERENCES users (id);
ALTER TABLE review_schedule ADD CONSTRAINT fk_review_schedule_lexical_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE review_schedule ADD CONSTRAINT fk_review_schedule_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE review_schedule ADD CONSTRAINT fk_review_schedule_source_training_session_id FOREIGN KEY (source_training_session_id) REFERENCES training_session (id);
ALTER TABLE review_schedule ADD CONSTRAINT fk_review_schedule_wrong_book_id FOREIGN KEY (wrong_book_id) REFERENCES wrong_book (id);
ALTER TABLE student_profile ADD CONSTRAINT fk_student_profile_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE teacher_profile ADD CONSTRAINT fk_teacher_profile_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE teaching_class ADD CONSTRAINT fk_teaching_class_teacher_user_id FOREIGN KEY (teacher_user_id) REFERENCES users (id);
ALTER TABLE teaching_class_student ADD CONSTRAINT fk_teaching_class_student_class_id FOREIGN KEY (teaching_class_id) REFERENCES teaching_class (id);
ALTER TABLE teaching_class_student ADD CONSTRAINT fk_teaching_class_student_student_user_id FOREIGN KEY (student_user_id) REFERENCES users (id);
ALTER TABLE training_item_result ADD CONSTRAINT fk_training_item_result_lexical_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE training_item_result ADD CONSTRAINT fk_training_item_result_plan_item_id FOREIGN KEY (plan_item_id) REFERENCES training_plan_item (id);
ALTER TABLE training_item_result ADD CONSTRAINT fk_training_item_result_session_id FOREIGN KEY (session_id) REFERENCES training_session (id);
ALTER TABLE training_plan ADD CONSTRAINT fk_training_plan_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE training_plan ADD CONSTRAINT fk_training_plan_source_diagnosis_session_id FOREIGN KEY (source_diagnosis_session_id) REFERENCES diagnosis_session (id);
ALTER TABLE training_plan ADD CONSTRAINT fk_training_plan_source_diagnosis_summary_id FOREIGN KEY (source_diagnosis_summary_id) REFERENCES diagnosis_summary (id);
ALTER TABLE training_plan_item ADD CONSTRAINT fk_training_plan_item_lexical_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE training_plan_item ADD CONSTRAINT fk_training_plan_item_plan_id FOREIGN KEY (plan_id) REFERENCES training_plan (id);
ALTER TABLE training_session ADD CONSTRAINT fk_training_session_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE training_session ADD CONSTRAINT fk_training_session_plan_id FOREIGN KEY (plan_id) REFERENCES training_plan (id);
ALTER TABLE user_role ADD CONSTRAINT fk_user_role_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE wrong_book ADD CONSTRAINT fk_wrong_book_lexical_pair_id FOREIGN KEY (lexical_pair_id) REFERENCES lexical_pair (id);
ALTER TABLE wrong_book ADD CONSTRAINT fk_wrong_book_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE wrong_book ADD CONSTRAINT fk_wrong_book_source_item_result_id FOREIGN KEY (source_item_result_id) REFERENCES training_item_result (id);
ALTER TABLE wrong_book ADD CONSTRAINT fk_wrong_book_source_training_session_id FOREIGN KEY (source_training_session_id) REFERENCES training_session (id);
ALTER TABLE practice_session ADD CONSTRAINT fk_practice_session_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE practice_session_answer ADD CONSTRAINT fk_practice_session_answer_session_id FOREIGN KEY (session_id) REFERENCES practice_session (id);

SET REFERENTIAL_INTEGRITY TRUE;
