spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.huashi.eftransfer: DEBUG
