spring:
  config:
    activate:
      on-profile: local
  flyway:
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.huashi.eftransfer: DEBUG
