spring:
  config:
    activate:
      on-profile: prod

server:
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.huashi.eftransfer: INFO
