spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://${APP_DB_HOST:localhost}:${APP_DB_PORT:3306}/${APP_DB_NAME:ef_transfer_app}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true&sslMode=${APP_DB_SSL_MODE:REQUIRED}

server:
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.huashi.eftransfer: INFO
